apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastchat-demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: fastchat-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: fastchat-demo
    spec:
      restartPolicy: Always
      containers:
      - name: controller
        image: jianshao/fastchat-demo:0.0.2
        ports:
        - containerPort: 21001
        command:
        - python
        - -m
        - fastchat.serve.controller
      - name: worker
        image: jianshao/fastchat-demo:0.0.2
        envFrom:
        - configMapRef:
            name: fastchat-env-cm
        ports:
        - containerPort: 21002
        command:
        - python
        - -m
        - fastchat.serve.model_worker
        - --model-path
        - $(model_path)
        - --device
        - cpu
        volumeMounts:
        - mountPath: /home/devel/.cache
          name: model-cache-dir
      - name: web
        image: jianshao/fastchat-demo:0.0.2
        ports:
        - containerPort: 7860
        command:
        - python
        - -m
        - fastchat.serve.gradio_web_server
      volumes:
      - name: model-cache-dir
        persistentVolumeClaim:
          claimName: model-cache-dir-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fastchat-demo
  labels:
    app: fastchat-demo
  namespace: demo
spec:
  ports:
  - name: http
    port: 7860
  selector:
    app: fastchat-demo
