apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-cache-dir-pv
  labels:
    type: local
spec:
  storageClassName: model-cache-dir
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/devel/.cache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo
  name: model-cache-dir-pvc
spec:
  storageClassName: model-cache-dir
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
