apiVersion: v1
kind: PersistentVolume
metadata:
  name: model_base_dir-pv
  labels:
    type: local
spec:
  storageClassName: model_base_dir
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/huggingface"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo
  name: model_base_dir-pvc
spec:
  storageClassName: model_base_dir
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
