version: "3"
services:
  controller:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}controller
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.controller
      - --host
      - 0.0.0.0
  worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}worker
    restart: unless-stopped
    depends_on:
      - controller
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://worker:21002
      - --model-names
      - gpt-3.5-turbo,text-embedding-ada-002
      - --model-path
      - ${model_path}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  openai:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}openai
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.openai_api_server
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
    ports:
      - 8000:8000
