version: "3"
services:
  controller:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}controller
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.controller
      - --host
      - 0.0.0.0
  embedding-worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}embedding-worker
    restart: unless-stopped
    depends_on:
      - controller
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      # - --debug
      # - DEBUG
      # - --load-8bit
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://embedding-worker:21002
      - --model-names
      - text-embedding-ada-002
      - --model-path
      - ${embedding_model_path}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  chat-worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}chat-worker
    restart: unless-stopped
    depends_on:
      - controller
    environment:
      - https_proxy=192.168.31.2:8123
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      # - --debug
      # - DEBUG
      # - --load-8bit
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://chat-worker:21002
      - --model-names
      - gpt-3.5-turbo
      - --model-path
      - ${chat_model_path}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  openai:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}openai
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.openai_api_server
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
    ports:
      - 8000:8000
  nextweb:
    image: yidadaa/chatgpt-next-web:v2.10.1
    container_name: ${container_name_prefix}nextweb
    restart: unless-stopped
    depends_on:
      - openai
    environment:
      - BASE_URL=http://openai:8000
    ports:
      - 3000:3000
