apiVersion: v1
kind: Service
metadata:
  name: openai-api
  labels:
    app: openai-api
  namespace: demo
spec:
  ports:
  - name: http-api
    port: 8000
  - name: http-web
    port: 3000
  selector:
    app: openai-api
