version: "3"
services:
  controller:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}controller
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.controller
      - --host
      - 0.0.0.0
  worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}worker
    restart: unless-stopped
    depends_on:
      - controller
    environment:
      - https_proxy=${https_proxy}
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      - --load-8bit
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://worker:21002
      - --model-path
      - ${model_path}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
  web:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}web
    restart: unless-stopped
    depends_on:
      - controller
      - worker
    command:
      - python
      - -m
      - fastchat.serve.gradio_web_server
      - --controller-url
      - http://controller:21001
      - --model-list-mode
      - reload
    ports:
      - 7860:7860
