apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-openai-api
  namespace: demo
spec:
  selector:
    matchLabels:
      app: lc-openai-api
  replicas: 1
  template:
    metadata:
      labels:
        app: lc-openai-api
    spec:
      restartPolicy: Always
      containers:
      - name: openai
        image: jianshao/llama-cpp-server:cpu
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /home/devel/.cache
          name: model-cache-dir
      - name: nextchat
        image: yidadaa/chatgpt-next-web:v2.11.3
        env:
        - name: BASE_URL
          value: http://localhost:8000
        ports:
        - containerPort: 3000
      volumes:
      - name: model-cache-dir
        persistentVolumeClaim:
          claimName: model-cache-dir-pvc
