version: "3"
services:
  openai:
    image: jianshao/llama-cpp-demo:${image_ver}
    container_name: ${container_name_prefix}openai
    restart: unless-stopped
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    environment:
      - https_proxy=http://192.168.31.2:8123
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  nextchat:
    image: yidadaa/chatgpt-next-web:v2.11.2
    container_name: ${container_name_prefix}nextchat
    restart: unless-stopped
    depends_on:
      - openai
    environment:
      - BASE_URL=http://openai:8000
    ports:
      - 3000:3000
