version: "3"
services:
  openai:
    image: jianshao/llama-cpp-server:${image_ver}
    container_name: ${container_name_prefix}openai
    restart: unless-stopped
    environment:
      - https_proxy=${https_proxy}
      - HF_REPO_ID=${HF_REPO_ID}
      - HF_MODEL_FILE=${HF_MODEL_FILE}
      - HF_MODEL_ALIAS=${HF_MODEL_ALIAS}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    ports:
      - 8000:8000
  nextchat:
    image: yidadaa/chatgpt-next-web:v2.11.3
    container_name: ${container_name_prefix}nextchat
    restart: unless-stopped
    depends_on:
      - openai
    environment:
      - BASE_URL=http://openai:8000
    ports:
      - 3000:3000
